"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
import time

def factorial():
	i=1
	j=2
	fac=[]
	final_list=[]
	fac.append(i)
	fac.append(j)
	z=i+j
	while(z<4000000):
		z=i+j
		fac.append(z)
		i=j
		j=z
	for n in fac:
		if(n%2==0):
			final_list.append(n)
	return sum(final_list)	
       
if __name__ == "__main__":
	start = time.clock()	
	print "Sum is"+ " " + str(factorial())
	print "Time taken"
	print time.clock() - start


